export const FETCH_CHART_REQUEST = "FETCH_CHART_REQUEST";
export type FETCH_CHART_REQUEST = typeof FETCH_CHART_REQUEST;

export const FETCH_CHART_SUCCESS = "FETCH_CHART_SUCCESS";
export type FETCH_CHART_SUCCESS = typeof FETCH_CHART_SUCCESS;

export const FETCH_CHART_FAILURE = "FETCH_CHART_FAILURE";
export type FETCH_CHART_FAILURE = typeof FETCH_CHART_FAILURE;
