export const FETCH_DATA_ALBUM_REQUEST = "FETCH_DATA_ALBUM_REQUEST";
export type FETCH_DATA_ALBUM_REQUEST = typeof FETCH_DATA_ALBUM_REQUEST;

export const FETCH_DATA_ALBUM_SUCCESS = "FETCH_DATA_ALBUM_SUCCESS";
export type FETCH_DATA_ALBUM_SUCCESS = typeof FETCH_DATA_ALBUM_SUCCESS;

export const FETCH_DATA_ALBUM_FAILURE = "FETCH_DATA_ALBUM_FAILURE";
export type FETCH_DATA_ALBUM_FAILURE = typeof FETCH_DATA_ALBUM_FAILURE;