export const FETCH_DATA_ARTIST_REQUEST = "FETCH_DATA_ARTIST_REQUEST";
export type FETCH_DATA_ARTIST_REQUEST = typeof FETCH_DATA_ARTIST_REQUEST;

export const FETCH_DATA_ARTIST_SUCCESS = "FETCH_DATA_ARTIST_SUCCESS";
export type FETCH_DATA_ARTIST_SUCCESS = typeof FETCH_DATA_ARTIST_SUCCESS;

export const FETCH_DATA_ARTIST_FAILURE = "FETCH_DATA_ARTIST_FAILURE";
export type FETCH_DATA_ARTIST_FAILURE = typeof FETCH_DATA_ARTIST_FAILURE;


export const FETCH_ARTIST_TRACKS_REQUEST = "FETCH_ARTIST_TRACKS_REQUEST";
export type FETCH_ARTIST_TRACKS_REQUEST = typeof FETCH_ARTIST_TRACKS_REQUEST;

export const FETCH_ARTIST_TRACKS_SUCCESS = "FETCH_ARTIST_TRACKS_SUCCESS";
export type FETCH_ARTIST_TRACKS_SUCCESS = typeof FETCH_ARTIST_TRACKS_SUCCESS;

export const FETCH_ARTIST_TRACKS_FAILURE = "FETCH_ARTIST_TRACKS_FAILURE";
export type FETCH_ARTIST_TRACKS_FAILURE = typeof FETCH_ARTIST_TRACKS_FAILURE;


export const FETCH_ARTIST_ALBUMS_REQUEST = "FETCH_ARTIST_ALBUMS_REQUEST";
export type FETCH_ARTIST_ALBUMS_REQUEST = typeof FETCH_ARTIST_ALBUMS_REQUEST;

export const FETCH_ARTIST_ALBUMS_SUCCESS = "FETCH_ARTIST_ALBUMS_SUCCESS";
export type FETCH_ARTIST_ALBUMS_SUCCESS = typeof FETCH_ARTIST_ALBUMS_SUCCESS;

export const FETCH_ARTIST_ALBUMS_FAILURE = "FETCH_ARTIST_ALBUMS_FAILURE";
export type FETCH_ARTIST_ALBUMS_FAILURE = typeof FETCH_ARTIST_ALBUMS_FAILURE;

export const PLAY_PAGE = "PLAY_PAGE";
export type PLAY_PAGE = typeof PLAY_PAGE;