export const FETCH_DATA_ARTIST_REQUEST = "FETCH_DATA_ARTIST_REQUEST";
export type FETCH_DATA_ARTIST_REQUEST = typeof FETCH_DATA_ARTIST_REQUEST;

export const FETCH_DATA_ARTIST_SUCCESS = "FETCH_DATA_ARTIST_SUCCESS";
export type FETCH_DATA_ARTIST_SUCCESS = typeof FETCH_DATA_ARTIST_SUCCESS;

export const FETCH_DATA_ARTIST_FAILURE = "FETCH_DATA_ARTIST_FAILURE";
export type FETCH_DATA_ARTIST_FAILURE = typeof FETCH_DATA_ARTIST_FAILURE;