export const FETCH_DATA_PLAYLIST_REQUEST = "FETCH_DATA_PLAYLIST_REQUEST";
export type FETCH_DATA_PLAYLIST_REQUEST = typeof FETCH_DATA_PLAYLIST_REQUEST;

export const FETCH_DATA_PLAYLIST_SUCCESS = "FETCH_DATA_PLAYLIST_SUCCESS";
export type FETCH_DATA_PLAYLIST_SUCCESS = typeof FETCH_DATA_PLAYLIST_SUCCESS;

export const FETCH_DATA_PLAYLIST_FAILURE = "FETCH_DATA_PLAYLIST_FAILURE";
export type FETCH_DATA_PLAYLIST_FAILURE = typeof FETCH_DATA_PLAYLIST_FAILURE;