export const SEARCH_DATA_REQUEST = "SEARCH_DATA_REQUEST";
export type SEARCH_DATA_REQUEST = typeof SEARCH_DATA_REQUEST;

export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export type SEARCH_DATA_SUCCESS = typeof SEARCH_DATA_SUCCESS;

export const SEARCH_DATA_FAILURE = "SEARCH_DATA_FAILURE";
export type SEARCH_DATA_FAILURE = typeof SEARCH_DATA_FAILURE;

