export const SEARCH_DATA_REQUEST = "SEARCH_DATA_REQUEST";
export type SEARCH_DATA_REQUEST = typeof SEARCH_DATA_REQUEST;

export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export type SEARCH_DATA_SUCCESS = typeof SEARCH_DATA_SUCCESS;

export const SEARCH_DATA_FAILURE = "SEARCH_DATA_FAILURE";
export type SEARCH_DATA_FAILURE = typeof SEARCH_DATA_FAILURE;

export const SEARCH_ARTIST_REQUEST = "SEARCH_ARTIST_REQUEST";
export type SEARCH_ARTIST_REQUEST = typeof SEARCH_ARTIST_REQUEST;

export const SEARCH_ARTIST_SUCCESS = "SEARCH_ARTIST_SUCCESS";
export type SEARCH_ARTIST_SUCCESS = typeof SEARCH_ARTIST_SUCCESS;

export const SEARCH_ARTIST_FAILURE = "SEARCH_ARTIST_FAILURE";
export type SEARCH_ARTIST_FAILURE = typeof SEARCH_ARTIST_FAILURE;

export const SAVE_SEARCHING_VALUE = "SAVE_SEARCHING_VALUE";
export type SAVE_SEARCHING_VALUE = typeof SAVE_SEARCHING_VALUE;

export const REDIRECT_BY_SEARCHING_VALUE = "REDIRECT_BY_SEARCHING_VALUE";
export type REDIRECT_BY_SEARCHING_VALUE = typeof REDIRECT_BY_SEARCHING_VALUE;

